#
# removes autogenerated types
#

rm index.swift uint.swift
rm  int8.swift  int16.swift  int32.swift  int64.swift  sat8.swift  sat16.swift
rm uint8.swift uint16.swift uint32.swift uint64.swift usat8.swift usat16.swift
rm real32.swift real64.swift
