#!/bin/bash

if [ $# -eq 0 ]; then
    echo "no input file given"
    exit -1
fi

in=$1
obj=$1.o
asm=$1.asm

if [ $# -eq 1 ]; then
    out=$1.out
    shift 1
elif [ $2 == "--" ]; then
        out=$1.out
        shift 2
elif [ $3 == "--" ]; then
        out=$2
        shift 3
else
    echo "usage: swiftc IN [OUT] [-- route-through-options}"
    exit -1
fi

./swift $in
gcc -ggdb -c test/lib.c -o test/lib.o
as $asm -o $obj


gcc -nostdlib -lc test/lib.o $obj -o $out $*
